name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GameOfLife
      run: |
        cmake .
        cmake --build .
    - name: console
      run: |
        cd console
        cmake .
    - name: game
      run: |
        cd game
        cmake .
    - name: printing_SDL2
      run: |
        sudo apt-get install libsdl2-2.0-0 libsdl2-dev libsdl2-image-2.0-0 libsdl2-image-dev
        cd printing_SDL2
        cmake .
