# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nafila/Desktop/DevTech/GameOfLife

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nafila/Desktop/DevTech/GameOfLife

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nafila/Desktop/DevTech/GameOfLife/CMakeFiles /home/nafila/Desktop/DevTech/GameOfLife/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nafila/Desktop/DevTech/GameOfLife/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameOfLife

# Build rule for target.
GameOfLife: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameOfLife
.PHONY : GameOfLife

# fast build rule for target.
GameOfLife/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/build
.PHONY : GameOfLife/fast

#=============================================================================
# Target rules for targets named console

# Build rule for target.
console: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 console
.PHONY : console

# fast build rule for target.
console/fast:
	$(MAKE) $(MAKESILENT) -f console/CMakeFiles/console.dir/build.make console/CMakeFiles/console.dir/build
.PHONY : console/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f game/CMakeFiles/game.dir/build.make game/CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named printing_SDL2

# Build rule for target.
printing_SDL2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 printing_SDL2
.PHONY : printing_SDL2

# fast build rule for target.
printing_SDL2/fast:
	$(MAKE) $(MAKESILENT) -f printing_SDL2/CMakeFiles/printing_SDL2.dir/build.make printing_SDL2/CMakeFiles/printing_SDL2.dir/build
.PHONY : printing_SDL2/fast

console/print_with_ansi.o: console/print_with_ansi.c.o

.PHONY : console/print_with_ansi.o

# target to build an object file
console/print_with_ansi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/console/print_with_ansi.c.o
.PHONY : console/print_with_ansi.c.o

console/print_with_ansi.i: console/print_with_ansi.c.i

.PHONY : console/print_with_ansi.i

# target to preprocess a source file
console/print_with_ansi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/console/print_with_ansi.c.i
.PHONY : console/print_with_ansi.c.i

console/print_with_ansi.s: console/print_with_ansi.c.s

.PHONY : console/print_with_ansi.s

# target to generate assembly for a file
console/print_with_ansi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/console/print_with_ansi.c.s
.PHONY : console/print_with_ansi.c.s

game/game.o: game/game.c.o

.PHONY : game/game.o

# target to build an object file
game/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/game/game.c.o
.PHONY : game/game.c.o

game/game.i: game/game.c.i

.PHONY : game/game.i

# target to preprocess a source file
game/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/game/game.c.i
.PHONY : game/game.c.i

game/game.s: game/game.c.s

.PHONY : game/game.s

# target to generate assembly for a file
game/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/game/game.c.s
.PHONY : game/game.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/main.c.s
.PHONY : main.c.s

printing_SDL2/print_with_sdl.o: printing_SDL2/print_with_sdl.c.o

.PHONY : printing_SDL2/print_with_sdl.o

# target to build an object file
printing_SDL2/print_with_sdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/printing_SDL2/print_with_sdl.c.o
.PHONY : printing_SDL2/print_with_sdl.c.o

printing_SDL2/print_with_sdl.i: printing_SDL2/print_with_sdl.c.i

.PHONY : printing_SDL2/print_with_sdl.i

# target to preprocess a source file
printing_SDL2/print_with_sdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/printing_SDL2/print_with_sdl.c.i
.PHONY : printing_SDL2/print_with_sdl.c.i

printing_SDL2/print_with_sdl.s: printing_SDL2/print_with_sdl.c.s

.PHONY : printing_SDL2/print_with_sdl.s

# target to generate assembly for a file
printing_SDL2/print_with_sdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameOfLife.dir/build.make CMakeFiles/GameOfLife.dir/printing_SDL2/print_with_sdl.c.s
.PHONY : printing_SDL2/print_with_sdl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GameOfLife"
	@echo "... console"
	@echo "... game"
	@echo "... printing_SDL2"
	@echo "... console/print_with_ansi.o"
	@echo "... console/print_with_ansi.i"
	@echo "... console/print_with_ansi.s"
	@echo "... game/game.o"
	@echo "... game/game.i"
	@echo "... game/game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... printing_SDL2/print_with_sdl.o"
	@echo "... printing_SDL2/print_with_sdl.i"
	@echo "... printing_SDL2/print_with_sdl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

